version: '3'
services:
  myapp:
    container_name: myapp-react-native
    tty: true
    stdin_open: true
    build:
      context: ./myapp
      dockerfile: ./Dockerfile
    volumes:
      - ./myapp:/myapp
      - node_modules:/myapp/node_modules
    ports:
      - "19000:19000"   # Metro server
      - "19001:19001"   # WebSocket (for device connections)
      - "19002:19002"   # Expo DevTools
      - "8081:8081"     # (Android metro, optional)
    # env_file: ./myapp/.env
  
volumes:
  node_modules:
